### ISSUE TITLE
Composer package not available

### ISSUE THREAD

**Issue by mickaelperrin** [bwp-codes/oxygen-cli#1]
Hi,

Thanks for that really useful plugin.

It worked well but I can't install it with composer 

```
 [InvalidArgumentException]
  Could not find a matching version of package bwp-codes/oxygen-cli. Check the package spelling, your
  version constraint and that the package is available in a stability which matches your minimum-stabi
  lity (dev).
```

and I didn't found it on wpackagist or packagist.

Do you have published it ?

**Comment by bwp-codes** [comment]
Hi @mickaelperrin,

Thank you for raising this issue! We have updated the readme to more clearly address the setup via composer.

Please note, that this plugin is not stable yet and might produce unexpected results. Also, it is completely untested with Version 4 of Oxygen Builder - so please be aware that we cannot guarantee that it works as one would expect.
If you like, please feel free to give us additional feedback if it is currently working for you, and if not, what breaks.

To make the repo available to be installed via composer, please explicitly add this repo to your `composer.json` as a `repository` like:
```
"repositories": [
    {
      "type": "git",
      "url": "git@github.com:bwp-codes/oxygen-cli.git",
    },
],
```

**Comment by mickaelperrin** [comment]
Thanks for the quick reply.

I know how to install it by adding repositories. This is just slowing the composer process, and I want to avoid that.

Hope you'll release it soon under packagist.

I already give it a shot under v4 of Oxygen and look at the code, and so far it looks like ok and functional.

**Comment by bwp-codes** [comment]
Thanks for your Feedback and your performance consideration! We appreciate your contribution!

Once we have had the time to test it more thoroughly with v4, we will release a v1 here and also publish it on packagist.

**Comment by bwp-codes** [comment]
Hi @mickaelperrin,

Thanks again for your support with this plugin! 😄 🙏 
We have now released it via packagist.org and adjusted the readme accordingly. 

It is now possible to just `composer require` it without specifiying an extra repo in your `composer.json`.

Kind Regards!
